### ISSUE TITLE
RFC: Seat price discounts

### ISSUE THREAD

**Issue by fireleaf-solutions** [getbooka/booka-issues#133]
Discount for bigger group sizes. For example:
1-2 Person: 2500.- p.p
3-4 Person: 2300.- p.p

The discount could be set by either % or x amount per seat

**Comment by davidsneighbour** [comment]
- [ ] set seat price per amount of a/c/i 
  - [ ] set via absolute price
  - [ ] set via percentage

**Comment by fireleaf-solutions** [comment]
Think also about how agent prices will be handled. Maybe have the option to:
- Bypass agent price from discount 
- Forward discount to agent price
- Set separate agent discount price
