### ISSUE TITLE
RFC: Receipts for Payments/ Paid Invoices 

### ISSUE THREAD

**Issue by fireleaf-solutions** [getbooka/booka-issues#134]
Add feature to create receipts for paid invoices. It would be handy to have a editable date field/calendar for the paid date. This is useful in case the payment has been made already but one forgot to add the payment to the system.
Hope that makes sense :)

**Comment by davidsneighbour** [comment]
If "one" forgot to add the payment to the system the actual payment is added at the datetime "one" does finally add it. The field can be shown, but system internal the payment/cashflow will be tracked when it's added. ok?

**Comment by fireleaf-solutions** [comment]
Should be fine. It’s just that if a payment was deposited to the bank account on 09.11 (Saturday) but it’s only being recognized and entered into Booka on 11.11 Monday, in should be possible to have the receipt state 09.11 as this was the actual date of deposit.
Therefore it would be handy to have a date which can be manually adjusted which is then the date on the payment receipt.
Makes sense?

**Comment by davidsneighbour** [comment]
Ok, so here is the idea ;)

### General Idea
- we issue receipts for `transactions` (each single payment flow) of invoices and bookings
- these receipts are simple and refer to the original invoice only by number, total and open balance
- a fully paid invoice can be issued **informal** with information about single payments
- the (new) invoice/booking detail pages (booking already does) show all single payments also printable

- [ ] create receipt format
- [ ] create options to configure the receipt (logo, notices etc.)
- [ ] create receipt on payment
- [ ] save receipt in PDF on file
- [ ] add payment option to action dropdown if `open balance` is > 0
- [ ] add receipt(s) option to action dropdown if `open balance` is < `total`

**Comment by davidsneighbour** [comment]
see #224
